export const soloNav = [
  { href: "/solo", label: "Solo Home", detail: "owner demo" },
  { href: "/solo/today", label: "Today", detail: "do first" },
  { href: "/solo/inbox", label: "Inbox", detail: "reply/call back" },
  { href: "/solo/jobs", label: "Jobs", detail: "follow-ups" },
  { href: "/solo/customers", label: "Customers", detail: "simple records" },
];

export const soloActions = [
  {
    slug: "call-back-sarah",
    tone: "urgent",
    status: "Urgent lead",
    title: "Call back Sarah Johnson",
    customer: "Sarah Johnson",
    detail: "Fresh enquiry waiting. Aura spotted it, ranked it, and prepared the safest next move.",
    meta: "18 mins waiting",
    value: "£280 est.",
    actionHref: "/solo/action/call-back-sarah",
    customerHref: "/solo/customers/sarah-johnson",
    actionLabel: "Open call-back",
  },
  {
    slug: "approve-first-reply",
    tone: "approval",
    status: "AI draft ready",
    title: "Check first reply",
    customer: "Sarah Johnson",
    detail: "Aura prepared a safe first reply with the basics. No prices, promises or awkward surprises.",
    meta: "Owner approval",
    value: "Safe reply ready",
    actionHref: "/solo/action/approve-first-reply",
    customerHref: "/solo/customers/sarah-johnson",
    actionLabel: "Check safe reply",
  },
  {
    slug: "send-friendly-follow-up",
    tone: "follow",
    status: "Follow-up due",
    title: "Send friendly follow-up",
    customer: "Mr Patel",
    detail: "A warm enquiry has gone quiet. Aura prepared a friendly nudge before it cools off.",
    meta: "4 days waiting",
    value: "£620 est.",
    actionHref: "/solo/action/send-friendly-follow-up",
    customerHref: "/solo/customers/mr-patel",
    actionLabel: "Open follow-up",
  },
  {
    slug: "request-reviews",
    tone: "review",
    status: "Reviews ready",
    title: "Request 2 reviews",
    customer: "Mrs Khan",
    detail: "Two happy customers are ready for a review ask. Nice and simple — no awkward chasing.",
    meta: "2 ready",
    value: "Proof building",
    actionHref: "/solo/action/request-reviews",
    customerHref: "/solo/customers/mrs-khan",
    actionLabel: "Open review task",
  },
] as const;

export const soloCustomers = [
  {
    slug: "sarah-johnson",
    initials: "SJ",
    name: "Sarah Johnson",
    status: "Urgent lead",
    need: "Fresh enquiry needs call-back and safe first reply.",
    area: "Salford",
    source: "Missed call + WhatsApp",
    value: "£280 est.",
    nextAction: "Call back and approve reply",
    actionHref: "/solo/action/call-back-sarah",
  },
  {
    slug: "mr-patel",
    initials: "MP",
    name: "Mr Patel",
    status: "Follow-up due",
    need: "A warm customer follow-up has been waiting four days.",
    area: "Manchester",
    source: "Website enquiry",
    value: "£620 est.",
    nextAction: "Send follow-up",
    actionHref: "/solo/action/send-friendly-follow-up",
  },
  {
    slug: "mrs-khan",
    initials: "MK",
    name: "Mrs Khan",
    status: "Review ready",
    need: "Completed service visit is ready for a friendly review ask.",
    area: "Stockport",
    source: "Completed job",
    value: "Proof item",
    nextAction: "Request review",
    actionHref: "/solo/action/request-reviews",
  },
  {
    slug: "tom-wilson",
    initials: "TW",
    name: "Tom Wilson",
    status: "Job today",
    need: "Today’s visit is confirmed and needs simple job visibility.",
    area: "Bolton",
    source: "Repeat customer",
    value: "£410 est.",
    nextAction: "Open job note",
    actionHref: "/solo/jobs",
  },
] as const;

export const soloActionDetails = [
  {
    slug: "call-back-sarah",
    label: "Call-back recovery",
    title: "Call back Sarah Johnson",
    customer: "Sarah Johnson",
    summary: "Aura spotted this as the first Solo action because it is recent, urgent and likely to be lost if ignored.",
    ownerAction: "Owner calls Sarah back or approves the safe first reply.",
    risk: "High — missed urgent repair enquiries are time-sensitive.",
    preparedByAura: [
      "Found the missed enquiry.",
      "Matched it to the customer record.",
      "Moved it to the top of Solo Today.",
      "Prepared a safe reply route.",
    ],
    ownerSteps: [
      "Call the customer back.",
      "Confirm postcode and access details.",
      "Avoid quoting or promising availability without checking.",
      "Mark the action handled in the demo.",
    ],
    backHref: "/solo/today",
    customerHref: "/solo/customers/sarah-johnson",
  },
  {
    slug: "approve-first-reply",
    label: "Owner approval",
    title: "Check first reply",
    customer: "Sarah Johnson",
    summary: "Aura prepared the safe first reply. You still control anything that could promise price, time or availability.",
    ownerAction: "Check the safe reply, tweak it if needed, then approve, edit or hold.",
    risk: "Medium — safe details are fine, but promises still need you.",
    preparedByAura: [
      "Prepared a short safe reply.",
      "Asked for the basic details needed to help properly.",
      "Avoided prices, promises and awkward surprises.",
      "Kept you in charge of anything risky.",
    ],
    ownerSteps: [
      "Read the draft.",
      "Check it does not promise price or availability.",
      "Approve or edit.",
      "Send manually in the real world later — demo only here.",
    ],
    backHref: "/solo/inbox",
    customerHref: "/solo/customers/sarah-johnson",
  },
  {
    slug: "send-friendly-follow-up",
    label: "Follow-up recovery",
    title: "Send friendly follow-up",
    customer: "Mr Patel",
    summary: "Aura found a warm opportunity that has gone quiet and prepared a friendly follow-up.",
    ownerAction: "Send a gentle follow-up or call the customer.",
    risk: "Medium — warm opportunities can be lost when follow-up is forgotten.",
    preparedByAura: [
      "Found the quiet opportunity.",
      "Checked the last customer message.",
      "Prepared a gentle chase.",
      "Kept it in Solo Jobs until handled.",
    ],
    ownerSteps: [
      "Review the follow-up.",
      "Send or call.",
      "Mark as waiting if no reply.",
      "Move back to Today if urgent.",
    ],
    backHref: "/solo/jobs",
    customerHref: "/solo/customers/mr-patel",
  },
  {
    slug: "request-reviews",
    label: "Review request",
    title: "Request 2 reviews",
    customer: "Mrs Khan",
    summary: "Aura found completed jobs that are ready for a simple review request.",
    ownerAction: "Send review requests for completed jobs.",
    risk: "Low — simple review request, no sensitive complaint or price promise.",
    preparedByAura: [
      "Found completed jobs.",
      "Prepared review request wording.",
      "Kept proof-building visible.",
      "Avoided fake review claims.",
    ],
    ownerSteps: [
      "Check the job is completed.",
      "Send the review request.",
      "Do not write or fake reviews.",
      "Use real reviews only in proof packs.",
    ],
    backHref: "/solo/jobs",
    customerHref: "/solo/customers/mrs-khan",
  },
] as const;

export function getSoloAction(slug: string) {
  return soloActionDetails.find((action) => action.slug === slug);
}

export function getSoloCustomer(slug: string) {
  return soloCustomers.find((customer) => customer.slug === slug);
}
