export const teamStats = [
  { label: "Unassigned", value: "2", detail: "needs an owner" },
  { label: "With team", value: "6", detail: "being handled" },
  { label: "Owner checks", value: "4", detail: "needs approval" },
  { label: "Handovers", value: "3", detail: "ready to use" },
] as const;

export const teamLanes = [
  {
    lane: "Unassigned",
    count: "2",
    items: [
      {
        slug: "assign-facebook-enquiry",
        title: "Facebook enquiry needs an owner",
        customer: "Maya Collins",
        detail: "Aura spotted a fresh enquiry with no owner. Better to grab it before it drifts.",
        owner: "Unassigned",
        action: "Assign owner",
        href: "/team/action/assign-facebook-enquiry",
        customerHref: "/team/customers/maya-collins",
      },
      {
        slug: "escalate-missed-call",
        title: "Missed call needs a decision",
        customer: "Daniel Reed",
        detail: "Fresh enquiry. Aura suggests owner callback before the lead cools off.",
        owner: "Unassigned",
        action: "Escalate",
        href: "/team/action/escalate-missed-call",
        customerHref: "/team/customers/daniel-reed",
      },
    ],
  },
  {
    lane: "With team",
    count: "6",
    items: [
      {
        slug: "open-handover-note",
        title: "Job handover note ready",
        customer: "Amelia Brooks",
        detail: "Aura summarised the useful bits so the next person is not guessing.",
        owner: "Marcus",
        action: "Open handover",
        href: "/team/action/open-handover-note",
        customerHref: "/team/customers/amelia-brooks",
      },
      {
        slug: "check-follow-up-owner",
        title: "Follow-up waiting on coordinator",
        customer: "Mr Patel",
        detail: "The customer has gone quiet. Aura prepared a friendly nudge for the team.",
        owner: "Leah",
        action: "Review nudge",
        href: "/team/action/check-follow-up-owner",
        customerHref: "/team/customers/mr-patel",
      },
    ],
  },
  {
    lane: "Owner checks",
    count: "4",
    items: [
      {
        slug: "review-owner-approval",
        title: "Reply needs owner approval",
        customer: "Emily Davis",
        detail: "Aura drafted the reply, but this one includes a promise. Owner checks it first.",
        owner: "John D",
        action: "Review approval",
        href: "/team/action/review-owner-approval",
        customerHref: "/team/customers/emily-davis",
      },
      {
        slug: "resolve-duplicate-reply",
        title: "Duplicate reply warning",
        customer: "Tom Wilson",
        detail: "Two people may reply to the same customer. Aura paused the second draft.",
        owner: "John D",
        action: "Fix duplicate",
        href: "/team/action/resolve-duplicate-reply",
        customerHref: "/team/customers/tom-wilson",
      },
    ],
  },
] as const;

export const teamActions = [
  {
    slug: "assign-facebook-enquiry",
    label: "Assignment",
    title: "Assign Facebook enquiry",
    customer: "Maya Collins",
    summary: "Aura found a fresh enquiry with no owner. Team mode makes sure it does not float around unseen.",
    auraPrepared: [
      "Moved the enquiry into the shared queue.",
      "Suggested an owner based on the work type.",
      "Prepared a short handover note.",
      "Kept promises and quotes out of the auto-reply.",
    ],
    teamSteps: [
      "Assign the enquiry.",
      "Add a short note if needed.",
      "Keep it visible until the customer gets a reply.",
    ],
    result: "Someone owns it. The customer is not left waiting.",
    backHref: "/team/assignments",
    customerHref: "/team/customers/maya-collins",
  },
  {
    slug: "escalate-missed-call",
    label: "Escalation",
    title: "Escalate missed call",
    customer: "Daniel Reed",
    summary: "Aura spotted a fresh missed call and recommends owner callback before the lead cools off.",
    auraPrepared: [
      "Flagged the missed call as time-sensitive.",
      "Prepared a short callback note.",
      "Kept it out of the normal queue until someone owns it.",
      "Left any promise or price decision for the owner.",
    ],
    teamSteps: [
      "Escalate to the owner.",
      "Add context if needed.",
      "Mark the callback handled once it is done.",
    ],
    result: "Fast team response without risky promises.",
    backHref: "/team/queue",
    customerHref: "/team/customers/daniel-reed",
  },
  {
    slug: "open-handover-note",
    label: "Handover",
    title: "Open handover note",
    customer: "Amelia Brooks",
    summary: "Aura prepared the useful bits so the next person can pick up the job without chasing context.",
    auraPrepared: [
      "Summarised the latest customer note.",
      "Pulled the next step into one place.",
      "Removed extra noise.",
      "Kept the handover short enough to actually read.",
    ],
    teamSteps: [
      "Read the handover.",
      "Confirm the next step.",
      "Mark it ready for the team member.",
    ],
    result: "Less guessing. Fewer repeat questions. Better handover.",
    backHref: "/team/queue",
    customerHref: "/team/customers/amelia-brooks",
  },
  {
    slug: "check-follow-up-owner",
    label: "Follow-up",
    title: "Review follow-up",
    customer: "Mr Patel",
    summary: "Aura found a quiet customer follow-up and prepared a friendly nudge for the team.",
    auraPrepared: [
      "Found the quiet follow-up.",
      "Prepared a friendly nudge.",
      "Linked it to the customer context.",
      "Kept it visible in the shared queue.",
    ],
    teamSteps: [
      "Review the nudge.",
      "Send or assign it.",
      "Bring the owner in if a promise is needed.",
    ],
    result: "The follow-up stays warm instead of vanishing into the day.",
    backHref: "/team/queue",
    customerHref: "/team/customers/mr-patel",
  },
  {
    slug: "review-owner-approval",
    label: "Owner check",
    title: "Review owner approval",
    customer: "Emily Davis",
    summary: "Aura drafted the reply, but it includes a promise. Team mode keeps it waiting for owner approval.",
    auraPrepared: [
      "Drafted the reply.",
      "Detected a promise in the wording.",
      "Stopped it from being treated as a normal reply.",
      "Moved it to owner checks.",
    ],
    teamSteps: [
      "Owner reviews the promise.",
      "Edit if needed.",
      "Approve only if the business can honour it.",
    ],
    result: "The team can prepare work without accidentally over-promising.",
    backHref: "/team/approvals",
    customerHref: "/team/customers/emily-davis",
  },
  {
    slug: "resolve-duplicate-reply",
    label: "Duplicate warning",
    title: "Fix duplicate reply warning",
    customer: "Tom Wilson",
    summary: "Aura spotted two people preparing replies to the same customer. Better to catch it before Tom gets two different answers.",
    auraPrepared: [
      "Detected two draft replies.",
      "Paused the second draft.",
      "Flagged the customer conversation.",
      "Kept the team from doubling up.",
    ],
    teamSteps: [
      "Choose who owns the reply.",
      "Remove the duplicate draft.",
      "Send one clear response.",
    ],
    result: "One customer. One clear reply. No awkward double message.",
    backHref: "/team/approvals",
    customerHref: "/team/customers/tom-wilson",
  },
] as const;

export const teamCustomers = [
  {
    slug: "maya-collins",
    initials: "MC",
    name: "Maya Collins",
    status: "Unassigned enquiry",
    owner: "Suggested: Sarah",
    detail: "Fresh social enquiry needs someone to take ownership.",
    nextAction: "Assign and reply",
    actionHref: "/team/action/assign-facebook-enquiry",
  },
  {
    slug: "daniel-reed",
    initials: "DR",
    name: "Daniel Reed",
    status: "Owner callback",
    owner: "John D",
    detail: "Fresh missed call needs a quick owner decision.",
    nextAction: "Escalate callback",
    actionHref: "/team/action/escalate-missed-call",
  },
  {
    slug: "amelia-brooks",
    initials: "AB",
    name: "Amelia Brooks",
    status: "Handover ready",
    owner: "Marcus",
    detail: "Customer context is ready for the next team member.",
    nextAction: "Open handover",
    actionHref: "/team/action/open-handover-note",
  },
  {
    slug: "mr-patel",
    initials: "MP",
    name: "Mr Patel",
    status: "Follow-up waiting",
    owner: "Leah",
    detail: "Quiet opportunity needs a friendly nudge.",
    nextAction: "Review follow-up",
    actionHref: "/team/action/check-follow-up-owner",
  },
  {
    slug: "emily-davis",
    initials: "ED",
    name: "Emily Davis",
    status: "Needs approval",
    owner: "John D",
    detail: "Prepared reply includes a promise and needs owner approval.",
    nextAction: "Review approval",
    actionHref: "/team/action/review-owner-approval",
  },
  {
    slug: "tom-wilson",
    initials: "TW",
    name: "Tom Wilson",
    status: "Duplicate warning",
    owner: "Sarah",
    detail: "Two draft replies were spotted before they reached the customer.",
    nextAction: "Fix duplicate reply",
    actionHref: "/team/action/resolve-duplicate-reply",
  },
] as const;

export function getTeamAction(slug: string) {
  return teamActions.find((action) => action.slug === slug);
}

export function getTeamCustomer(slug: string) {
  return teamCustomers.find((customer) => customer.slug === slug);
}
